pipeline {
  agent any
  tools {
      maven 'maven'
      // dockerTool 'Docker'  
    }
  stages {
    stage('Checkout') {
      steps {
        sh 'echo passed'
      }
    }
    stage('Build and Test') {
      steps {
        sh 'cd springCoreDemo && mvn clean package' 
      }
    }
    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://172.16.147.131:9000/"
      }
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh 'cd springCoreDemo && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
        }
      }
    }
    stage('Build Docker Image and push to Harbor') {
      environment {
        DOCKER_IMAGE = 'testimage'
        REGISTRY = 'http://172.16.147.131:8081'
        HARBOR_NAMESPACE = 'testproject'
        HARBOR_CREDENTIAL = credentials('harbor_login')
      }
      steps {
        script {
            sh 'cd springCoreDemo && docker build -t $REGISTRY/$HARBOR_NAMESPACE/${DOCKER_IMAGE}:${env.BUILD_NUMBER} .'
            sh 'docker push $REGISTRY/$HARBOR_NAMESPACE/${DOCKER_IMAGE}:${env.BUILD_NUMBER}'
        }
      }
    }
  }
}
